let mapleader=" "

set langmap=qq,dw,re,wr,bt,jy,fu,ui,po,\;p,aa,ss,hd,tf,gg,yh,nj,ek,ol,i\;,zz,xx,mc,cv,vb,kn,lm,QQ,DW,RE,WR,BT,JY,FU,UI,PO,\:P,AA,SS,HD,TF,GG,YH,NJ,EK,OL,I\:,ZZ,XX,MC,CV,VB,KN,LM

nnoremap <C-d> <del>
inoremap <C-l> <ESC>
inoremap <C-,> <Left>
inoremap <C-.> <Right>
inoremap <C-S-lt> <Down>
inoremap <C-S->> <Up>

nnoremap <leader>w :w!<CR>
nnoremap <leader>q :q!<CR>


vnoremap < <gv
vnoremap > >gv

nnoremap S viw

set clipboard=unnamedplus
set clipboard+=unnamed
