let mapleader=" "

nnoremap y h
nnoremap h y
nnoremap n j
nnoremap j n
nnoremap e k
nnoremap k e
nnoremap o l
nnoremap l o


nnoremap Y H
nnoremap N J
nnoremap J N
nnoremap E K
nnoremap K E
nnoremap O L
nnoremap L O


xnoremap y h
xnoremap h y
xnoremap n j
xnoremap j n
xnoremap e k
xnoremap k e
xnoremap o l
xnoremap l o


onoremap h y
onoremap y h



nnoremap N 3j
nnoremap E 3k


nnoremap S viw

set clipboard=unnamedplus
