let mapleader=" "

set langmap=yh,hy,nj,jn,ek,ke,ol,lo,YH,HY,NJ,JN,EK,KE,OL,LO
nnoremap <C-d> <del>
inoremap <C-l> <ESC>
inoremap <C-,> <Left>
inoremap <C-.> <Right>
inoremap <C-S-lt> <Down>
inoremap <C-S->> <Up>

nnoremap <leader>w :w!<CR>
nnoremap <leader>q :q!<CR>


vnoremap < <gv
vnoremap > >gv

nnoremap S viw

set clipboard=unnamedplus
set clipboard+=unnamed
